services:
  react-native-app:
    build: .
    container_name: react-native-app
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
      - "8081:8081"
      - "8082:8082"
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - $HOME/Library/Android/sdk:/root/Android/sdk

    stdin_open: true
    tty: true
    networks:
      - rn_network

networks:
  rn_network:
    driver: bridge

